In [10]:
import pandas as pd

# 파일 경로 설정
file_path = './seoul_commerce_data_20241221_131311.csv'

# CSV 파일 불러오기
df = pd.read_csv(file_path)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 875 entries, 0 to 874
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   지역명           875 non-null    object
 1   2022년2분기_전체   875 non-null    int64
 2   2022년2분기_1층   875 non-null    int64
 3   2022년2분기_1층외  875 non-null    int64
 4   2023년2분기_전체   875 non-null    int64
 5   2023년2분기_1층   875 non-null    int64
 6   2023년2분기_1층외  875 non-null    int64
 7   2024년2분기_전체   875 non-null    int64
 8   2024년2분기_1층   875 non-null    int64
 9   2024년2분기_1층외  875 non-null    int64
 10  수집_일시         875 non-null    object
 11  데이터_구분        875 non-null    object
dtypes: int64(9), object(3)
memory usage: 82.2+ KB

,지역명,2022년2분기_전체,2022년2분기_1층,2022년2분기_1층외,2023년2분기_전체,2023년2분기_1층,2023년2분기_1층외,2024년2분기_전체,2024년2분기_1층,2024년2분기_1층외,수집_일시,데이터_구분
0,종로구,198534,226443,170624,197186,229859,164512,195617,230674,160559,2024-12-21 13:13:11,구
1,청운효자동,147878,212258,83498,133334,206441,60228,152054,188588,115520,2024-12-21 13:13:11,동
2,사직동,162108,217048,107167,141193,188607,93778,184123,235516,132729,2024-12-21 13:13:11,동
3,삼청동,161693,180283,143103,169873,169873,0,153171,153171,0,2024-12-21 13:13:11,동
4,부암동,74155,93432,54879,109504,109504,0,98167,115405,80929,2024-12-21 13:13:11,동

In [13]:
import pandas as pd

# '데이터_구분'이 '구'인 행만 필터링
gu_df = df[df['데이터_구분'] == '구']

# 결과 확인
print(gu_df.head())

# 필요한 경우 CSV로 저장
gu_df.to_csv('./gu_data_only.csv', index=False, encoding='utf-8-sig')

    지역명  2022년2분기_전체  2022년2분기_1층  2022년2분기_1층외  2023년2분기_전체  2023년2분기_1층  \
0   종로구       198534       226443        170624       197186       229859
35   중구       240311       253968        226655       292292       307381
46  청구동       161939       221408        102470       160147       139527
66  용산구       137701       150920        124483       142058       167407
99  성동구       134990       154451        115530       225218       234169

    2023년2분기_1층외  2024년2분기_전체  2024년2분기_1층  2024년2분기_1층외                수집_일시  \
0         164512       195617       230674        160559  2024-12-21 13:13:11
35        277204       269374       282431        256317  2024-12-21 13:13:11
46        180766       215947       221091        210803  2024-12-21 13:13:11
66        116709       125065       140285        109845  2024-12-21 13:13:11
99        216267       136247       146129        126364  2024-12-21 13:13:11

   데이터_구분
0       구
35      구
46      구
66      구
99      구

In [17]:
# "2024년"으로 시작하는 열만 선택
columns_2024 = [col for col in df.columns if '2024년' in col]
gu_df_2024 = gu_df[['지역명'] + columns_2024]

# 결과 확인
# print(gu_df_2024.head())

# 필요하면 CSV로 저장
# df_2024.to_csv('./data_2024_only.csv', index=False, encoding='utf-8-sig')

gu_df_2024

      지역명  2024년2분기_전체  2024년2분기_1층  2024년2분기_1층외
0     종로구       195617       230674        160559
35     중구       269374       282431        256317
46    청구동       215947       221091        210803
66    용산구       125065       140285        109845
99    성동구       136247       146129        126364
134   광진구       106244       127395         85092
147  구의1동       102738       128292         77185
148  구의2동       107444       132907         81981
149  구의3동       120447       143766         97129
165  동대문구        91638       115398         67878
194   중랑구        89195       105403         72986
227   성북구       111710       126437         96983
268   강북구        90963       107986         73940
295   도봉구       105693       121776         89610
324   노원구       115201       142752         87650
363   은평구       100741       116360         85123
369   구산동        80501       101468         59534
396  서대문구       134820       140348        129292
425   마포구       144081       168276        119886
458   양천구       108209       129875         86542
495   강서구       129606       155766        103446
536   구로구       130869       149241        112497
538  구로1동       142798       156147        129448
539  구로2동       112400       128389         96411
540  구로3동       178435       229851        127019
541  구로4동       124059       126447        121671
542  구로5동       129466       151576        107357
569   금천구       115814       138293         93334
590  영등포구       116223       129352        103093
627   동작구       140897       175471        106323
658   관악구       119153       140018         98289
701   서초구       142327       157421        127233
738   강남구       181017       199480        162554
742  압구정동       188933       255426        122440
783   송파구       130984       153919        108050
838   강동구       119185       140386         97985